sudo: required
dist: trusty
language: CSharp
mono:
  - latest
install:
  - sudo apt-get -y install unzip curl
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade -r coreclr
  - dnu  --verbose restore
script:
  - dnx Toucan/test/Toucan.Tests/project.json test -parallel none
 